apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: worker-to-coordinator
  namespace: databend-flight-chaos
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - databend-flight-chaos
    labelSelectors:
      chaos-role: worker
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - databend-flight-chaos
      labelSelectors:
        chaos-role: coordinator
