DROP DATABASE IF EXISTS db1;

CREATE DATABASE db1;
USE db1;

CREATE TABLE IF NOT EXISTS t1(a int, b varchar) Engine = fuse;
SELECT * FROM system.tables WHERE database='db1';

DROP TABLE t1;
DROP TABLE IF EXISTS t1;
DROP TABLE t1; -- {ErrorCode 1025}

DROP DATABASE db1;

DROP DATABASE IF EXISTS db1;

DROP DATABASE db1; -- {ErrorCode 1003}
