// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Logs from this module will show up as "[VACUUM] ...".
databend_common_tracing::register_module_tag!("[VACUUM]");

use std::cmp::max;
use std::cmp::min;
use std::collections::HashMap;
use std::collections::HashSet;
use std::collections::VecDeque;
use std::future::Future;
use std::sync::Arc;
use std::time::Instant;
use std::time::SystemTime;

use chrono::DateTime;
use chrono::Duration;
use chrono::TimeDelta;
use chrono::Utc;
use databend_common_catalog::catalog::Catalog;
use databend_common_catalog::table::TableExt;
use databend_common_catalog::table_context::TableContext;
use databend_common_exception::ErrorCode;
use databend_common_exception::Result;
use databend_common_meta_app::schema::DropTableTagReq;
use databend_common_meta_app::schema::LeastVisibleTime;
use databend_common_meta_app::schema::ListTableTagsReq;
use databend_common_meta_app::schema::TableInfo;
use databend_common_meta_app::schema::least_visible_time_ident::LeastVisibleTimeIdent;
use databend_enterprise_vacuum_handler::VacuumHandlerWrapper;
use databend_storages_common_cache::Table;
use databend_storages_common_cache::TableSnapshot;
use databend_storages_common_table_meta::meta::Location;
use databend_storages_common_table_meta::meta::VACUUM2_OBJECT_KEY_PREFIX;
use databend_storages_common_table_meta::meta::is_uuid_v7;
use databend_storages_common_table_meta::meta::uuid_from_date_time;
use futures_util::StreamExt;
use futures_util::TryStreamExt;
use futures_util::stream;
use log::info;
use log::warn;
use opendal::Entry;
use opendal::ErrorKind;
use opendal::Operator;
use tokio::sync::Semaphore;

use crate::FuseTable;
use crate::RetentionPolicy;
use crate::io::MetaReaders;
use crate::io::SnapshotHistoryReader;
use crate::io::SnapshotsIO;
use crate::io::TableMetaLocationGenerator;

/// An assumption of the maximum duration from the time the first block is written to the time the
/// snapshot is written.
///
/// To handle the situation during an upgrade where some nodes may not be able to upgrade in time to
/// a version that includes the vacuum2 logic, we introduce this assumption. It is used in two places:
///
/// - When determining whether a snapshot object generated by an old version node can be cleaned up
///
///   Snapshots whose object key does not start with `VACUUM2_OBJECT_KEY_PREFIX` are all created by
///   nodes of previous versions (do not support vacuum2). For such snapshot objects, if their
///   timestamp is less than
///   `GC_root's timestamp - ASSUMPTION_MAX_TXN_DURATION`
///   we consider them safe to delete.
///
///   Generally speaking, if a snapshot from an old version was created a sufficiently long time
///   before the gc root, it would not be successfully committed after the gc root; this way, we
///   avoid deleting a snapshot object produced by an ongoing (not yet committed) transaction.
///
/// - When determining whether a segment/block object generated by an old version query node can be
///   cleaned up
///
///   Similarly, if a segment/block was created at a time sufficiently long before the gc root and
///   is not referenced by the gc root, then it will not be referenced by a snapshot that can be
///   successfully committed after the gc root, and safe to delete.
///
/// NOTE:
///   If this assumption does not hold, it may lead to table data becoming inaccessible:
///   snapshots may become inaccessible, or some data may become unavailable.
///
///   If the entire cluster is upgraded to the new version that includes the vacuum2 logic,
///   the above risks will not exist.
pub const ASSUMPTION_MAX_TXN_DURATION: Duration = Duration::days(3);

fn retention_cutoff(
    now: DateTime<Utc>,
    latest_snapshot_timestamp: DateTime<Utc>,
    retention_period: TimeDelta,
) -> DateTime<Utc> {
    min(now - retention_period, latest_snapshot_timestamp)
}

/// One concurrency budget shared by owner selection and all descendant metadata/history reads.
/// A permit covers an entire table scan; predecessor reads within that scan remain sequential.
pub struct VacuumConcurrency {
    permits: Semaphore,
    limit: usize,
}

impl VacuumConcurrency {
    pub fn new(limit: usize) -> Self {
        let limit = limit.max(1);
        Self {
            permits: Semaphore::new(limit),
            limit,
        }
    }

    pub async fn run<T: Send>(&self, work: impl Future<Output = Result<T>> + Send) -> Result<T> {
        let _permit = self
            .permits
            .acquire()
            .await
            .expect("the vacuum concurrency budget is never closed");
        work.await
    }
}

pub struct SnapshotGcSelection {
    pub gc_root: Arc<TableSnapshot>,
    pub snapshots_to_gc: Vec<String>,
    pub gc_root_meta_ts: DateTime<Utc>,
    pub gc_root_path: String,
    pub lvt: LeastVisibleTime,
}

#[derive(Clone, Copy)]
enum CloneDescendantMarkMode {
    /// Base-data VACUUM: apply retention and return fences for atomic publication.
    Vacuum,
    /// Derived-file cleanup: retain all publishable history and do not advance LVTs.
    ReferenceOnly,
}

impl CloneDescendantMarkMode {
    fn advances_lvt(self) -> bool {
        matches!(self, Self::Vacuum)
    }
}

pub struct CloneDescendantTagSource {
    table_id: u64,
    operator: Operator,
}

#[derive(Default)]
pub struct CloneDescendantMark {
    pub descendant_ids: HashSet<u64>,
    pub lvt_updates: Vec<(u64, u64, LeastVisibleTime)>,
    /// Stable table identity and storage operator reused only for the post-publication tag scan.
    pub tag_sources: Vec<CloneDescendantTagSource>,
}

/// Object storage supported by Databend is expected to return entries sorted in ascending lexicographical
/// order by object key. Databend leverages this property to enhance the efficiency and thoroughness
/// of the vacuum process.
///
/// The safety of the vacuum algorithm does not depend on this ordering.
async fn general_list_until_prefix(
    dal: &Operator,
    path: &str,
    until: &str,
    need_one_more: bool,
    gc_root_meta_ts: Option<DateTime<Utc>>,
) -> Result<Vec<Entry>> {
    let mut lister = dal.lister(path).await?;
    let mut paths = vec![];
    while let Some(entry) = lister.try_next().await? {
        if entry.metadata().is_dir() {
            continue;
        }
        if entry.path() >= until {
            info!("entry path: {} >= until: {}", entry.path(), until);
            if need_one_more {
                paths.push(entry);
            }
            break;
        }
        if gc_root_meta_ts.is_none()
            || is_gc_candidate_segment_block(&entry, dal, gc_root_meta_ts.unwrap()).await?
        {
            paths.push(entry);
        }
    }
    Ok(paths)
}

/// If storage is backed by FS, we prioritize thoroughness over efficiency (though efficiency loss
/// is usually not significant). All entries are fetched and sorted before extracting the prefix entries.
async fn fs_list_until_prefix(
    dal: &Operator,
    path: &str,
    until: &str,
    need_one_more: bool,
    gc_root_meta_ts: Option<DateTime<Utc>>,
) -> Result<Vec<Entry>> {
    // Fetch ALL entries from the path and sort them by path in lexicographical order.
    let mut lister = dal.lister(path).await?;
    let mut entries = Vec::new();
    while let Some(item) = lister.try_next().await? {
        if item.metadata().is_file() {
            entries.push(item);
        }
    }
    entries.sort_by(|l, r| l.path().cmp(r.path()));

    // Extract entries up to the `until` path, respecting lexicographical order.
    let mut res = Vec::new();
    for entry in entries {
        if entry.path() >= until {
            info!("entry path: {} >= until: {}", entry.path(), until);
            if need_one_more {
                res.push(entry);
            }
            break;
        }
        if gc_root_meta_ts.is_none()
            || is_gc_candidate_segment_block(&entry, dal, gc_root_meta_ts.unwrap()).await?
        {
            res.push(entry);
        }
    }

    Ok(res)
}

/// Check if an entry is a candidate for garbage collection
pub async fn is_gc_candidate_segment_block(
    entry: &Entry,
    op: &Operator,
    gc_root_meta_ts: DateTime<Utc>,
) -> Result<bool> {
    let path = entry.path();
    let last_part = path.rsplit('/').next().unwrap();
    if last_part.starts_with(VACUUM2_OBJECT_KEY_PREFIX) {
        return Ok(true);
    }
    let last_modified = if let Some(v) = entry.metadata().last_modified() {
        v
    } else {
        let path = entry.path();
        let meta = op.stat(path).await?;
        meta.last_modified().ok_or_else(|| {
            ErrorCode::StorageOther(format!(
                "Failed to get `last_modified` metadata of the entry '{}'",
                path
            ))
        })?
    };
    let last_modified = DateTime::<Utc>::from(SystemTime::from(last_modified));
    Ok(last_modified + ASSUMPTION_MAX_TXN_DURATION < gc_root_meta_ts)
}

impl FuseTable {
    /// Protect live table-tag references from VACUUM2 and remove expired tags.
    pub async fn protect_table_tag_references(
        &self,
        catalog: &Arc<dyn Catalog>,
        root_snapshot_location: &str,
        snapshot_files_to_gc: &mut Vec<String>,
        protected_segments: &mut HashSet<Location>,
    ) -> Result<()> {
        let now = Utc::now();
        let tags = catalog
            .list_table_tags(ListTableTagsReq {
                table_id: self.get_id(),
                include_expired: true,
            })
            .await?;

        let mut protected_snapshot_locs = HashSet::new();
        for (tag_name, seq_tag) in tags {
            if seq_tag
                .data
                .expire_at
                .is_some_and(|expire_at| expire_at <= now)
            {
                if let Err(error) = catalog
                    .drop_table_tag(DropTableTagReq {
                        table_id: self.get_id(),
                        tag_name,
                        seq: Some(seq_tag.seq),
                    })
                    .await
                {
                    warn!(
                        "drop expired tag failed, ignored, table: {}, err: {}",
                        self.table_info.desc, error
                    );
                }
                continue;
            }

            let tag_snapshot_loc = seq_tag.data.snapshot_loc;
            if tag_snapshot_loc.as_str() < root_snapshot_location {
                if let Some(snapshot) =
                    SnapshotsIO::read_snapshot_for_vacuum(self.get_operator(), &tag_snapshot_loc)
                        .await?
                {
                    protected_segments.extend(snapshot.segments.iter().cloned());
                }
                protected_snapshot_locs.insert(tag_snapshot_loc);
            }
        }

        snapshot_files_to_gc.retain(|path| !protected_snapshot_locs.contains(path));
        Ok(())
    }

    pub async fn vacuum_table(
        &self,
        ctx: Arc<dyn TableContext>,
        vacuum_handler: &VacuumHandlerWrapper,
        respect_flash_back: bool,
    ) {
        warn!(
            "Vacuuming table: {}, ident: {}",
            self.table_info.name, self.table_info.ident
        );

        if let Err(e) = vacuum_handler
            .do_vacuum2(self, ctx, respect_flash_back)
            .await
        {
            // Vacuum in a best-effort manner, errors are ignored
            warn!("Vacuum table {} failed : {}", self.table_info.name, e);
        } else {
            info!("Vacuum table {} done", self.table_info.name);
        }
    }

    pub fn vacuum2_until_prefix(path: &str, until: DateTime<Utc>) -> String {
        let uuid = uuid_from_date_time(until);
        let uuid_str = uuid.simple().to_string();

        // extract the most significant 48 bits, which is 12 characters
        let timestamp_component = &uuid_str[..12];
        format!(
            "{}{}{}",
            path, VACUUM2_OBJECT_KEY_PREFIX, timestamp_component
        )
    }

    /// List files until a specific timestamp
    ///
    /// This implementation uses UUID v7 timestamp extraction for precise filtering.
    /// Used by vacuum2.
    pub async fn list_files_until_timestamp(
        &self,
        path: &str,
        until: DateTime<Utc>,
        need_one_more: bool,
        gc_root_meta_ts: Option<DateTime<Utc>>,
    ) -> Result<Vec<Entry>> {
        let until = Self::vacuum2_until_prefix(path, until);
        self.list_files_until_prefix(path, &until, need_one_more, gc_root_meta_ts)
            .await
    }

    /// List files until a specific location/prefix
    ///
    /// This implementation handles different storage schemes (FS vs object storage) and
    /// includes gc_root_meta_ts checking for safe vacuum operations.
    pub async fn list_files_until_prefix(
        &self,
        path: &str,
        until: &str,
        need_one_more: bool,
        gc_root_meta_ts: Option<DateTime<Utc>>,
    ) -> Result<Vec<Entry>> {
        info!("Listing files until prefix: {}", until);
        let dal = self.get_operator_ref();

        match dal.info().scheme() {
            "fs" => fs_list_until_prefix(dal, path, until, need_one_more, gc_root_meta_ts).await,
            _ => general_list_until_prefix(dal, path, until, need_one_more, gc_root_meta_ts).await,
        }
    }

    /// Visit committed history to a time boundary (or the anchor if no boundary exists).
    /// No object-directory listing or LVT reads happen here. The visitor lets descendant
    /// protection collect references without allocating a mark set in the owner-only path.
    async fn select_snapshot_history_gc_root<F>(
        &self,
        ctx: &Arc<dyn TableContext>,
        head: (Arc<TableSnapshot>, u64),
        boundary: Option<DateTime<Utc>>,
        snapshot_limit: Option<usize>,
        mut visit: F,
    ) -> Result<(Arc<TableSnapshot>, u64)>
    where
        F: FnMut(&TableSnapshot) + Send,
    {
        let reader = MetaReaders::table_snapshot_reader(self.get_operator());
        let location_gen = self.meta_location_generator();
        let previous = match head.0.prev_snapshot_id {
            Some((id, version)) => reader.snapshot_history(
                location_gen.gen_snapshot_location(&id, version)?,
                version,
                location_gen.clone(),
            ),
            None => Box::pin(stream::empty()),
        };
        // The caller already read the head to calculate the retention boundary.
        let mut history = previous;
        let mut head = Some(head);
        let abort_checker = ctx.clone().get_abort_checker();
        let mut count = 0;
        loop {
            abort_checker.try_check_aborting()?;
            // snapshot_history also ends on NotFound. Only an observed anchor or boundary
            // completes this selection; a missing head or an unproven gap must stop GC.
            let (snapshot, version) = if let Some(head) = head.take() {
                head
            } else {
                history.try_next().await?.ok_or_else(|| {
                    ErrorCode::StorageNotFound(format!(
                        "table {} snapshot history ended before its GC boundary or anchor",
                        self.get_id()
                    ))
                })?
            };
            let timestamp = snapshot.timestamp.ok_or_else(|| {
                ErrorCode::Internal(format!(
                    "table {} snapshot {} has no timestamp",
                    self.get_id(),
                    snapshot.snapshot_id
                ))
            })?;
            visit(&snapshot);
            count += 1;
            if snapshot.prev_snapshot_id.is_none()
                || boundary.is_some_and(|time| timestamp <= time)
                || snapshot_limit.is_some_and(|limit| count >= limit.max(1))
            {
                return Ok((snapshot, version));
            }
        }
    }

    async fn protect_table_tags(
        table_id: u64,
        operator: &Operator,
        catalog: &Arc<dyn Catalog>,
        segments: &mut HashSet<Location>,
    ) -> Result<()> {
        let tags = catalog
            .list_table_tags(ListTableTagsReq {
                table_id,
                include_expired: false,
            })
            .await?;
        for (_tag_name, seq_tag) in tags {
            // Tag listing and object reads are not atomic. A listed tag may be dropped or
            // expire before this read, allowing another GC to remove its snapshot. Tolerate
            // NotFound without revalidating the tag: this scan is not a strongly consistent
            // tag view. Other storage errors still abort GC.
            if let Some(snapshot) =
                SnapshotsIO::read_snapshot_for_vacuum(operator.clone(), &seq_tag.data.snapshot_loc)
                    .await?
            {
                segments.extend(snapshot.segments.iter().cloned());
            }
        }
        Ok(())
    }

    /// Validate a clone group's binding graph and return descendants of `source_table_id`.
    /// Malformed, cyclic, or disconnected bindings fail closed.
    pub fn clone_descendant_ids(
        clone_group_id: u64,
        source_table_id: u64,
        bindings: &[(u64, u64)],
    ) -> Result<HashSet<u64>> {
        let clone_ids = bindings
            .iter()
            .map(|(table_id, _)| *table_id)
            .collect::<HashSet<_>>();
        // Each member is created by exactly one direct source. A repeated child ID means the
        // lineage is corrupted, and it is also what would let a cycle stay reachable from the
        // group root, making an owner appear inside its own descendant set.
        if clone_ids.len() != bindings.len() {
            return Err(ErrorCode::Internal(format!(
                "clone group {} has a member with more than one direct source",
                clone_group_id
            )));
        }
        let mut children = HashMap::<u64, Vec<u64>>::new();
        for (table_id, source_id) in bindings {
            children.entry(*source_id).or_default().push(*table_id);
        }

        let descendants_of = |root| {
            let mut queue = VecDeque::from([root]);
            let mut descendants = HashSet::new();
            while let Some(source_id) = queue.pop_front() {
                if let Some(child_ids) = children.get(&source_id) {
                    for child_id in child_ids {
                        if descendants.insert(*child_id) {
                            queue.push_back(*child_id);
                        }
                    }
                }
            }
            descendants
        };

        // A malformed or disconnected lineage can hide a live member from descendant protection.
        // Validate the entire binding graph using IDs only and fail closed before reading metadata.
        let connected = descendants_of(clone_group_id);
        if connected != clone_ids
            || connected.contains(&clone_group_id)
            || (source_table_id != clone_group_id && !clone_ids.contains(&source_table_id))
        {
            return Err(ErrorCode::Internal(format!(
                "clone group {} has malformed or disconnected lineage for table {}",
                clone_group_id, source_table_id
            )));
        }

        Ok(if source_table_id == clone_group_id {
            connected
        } else {
            descendants_of(source_table_id)
        })
    }

    fn bound_descendant_missing_meta<T>(
        descendants: &[(u64, Option<T>)],
        bindings: &[(u64, u64)],
    ) -> Option<u64> {
        let missing_ids = descendants
            .iter()
            .filter_map(|(id, meta)| meta.is_none().then_some(*id))
            .collect::<HashSet<_>>();
        bindings
            .iter()
            .find_map(|(id, _)| missing_ids.contains(id).then_some(*id))
    }

    /// Mark clone descendants using their retention policy and return the LVT fences that must be
    /// published atomically before sweeping. Existing bindings always use this single GC path.
    pub async fn mark_clone_descendants<T>(
        &self,
        ctx: Arc<dyn TableContext>,
        catalog: &Arc<dyn Catalog>,
        segments: &mut HashSet<Location>,
        concurrency: &VacuumConcurrency,
        status_callback: T,
    ) -> Result<CloneDescendantMark>
    where
        T: Fn(String),
    {
        self.mark_clone_descendant_references(
            ctx,
            catalog,
            segments,
            CloneDescendantMarkMode::Vacuum,
            concurrency,
            status_callback,
        )
        .await
    }

    async fn mark_one_clone_descendant(
        ctx: Arc<dyn TableContext>,
        catalog: Arc<dyn Catalog>,
        table_info: TableInfo,
        observed_lvt: Option<(u64, Option<DateTime<Utc>>)>,
        scan_time: DateTime<Utc>,
        mode: CloneDescendantMarkMode,
    ) -> Result<(
        u64,
        u64,
        LeastVisibleTime,
        HashSet<Location>,
        CloneDescendantTagSource,
    )> {
        let table_id = table_info.ident.table_id;
        let (lvt_seq, lvt) = observed_lvt.ok_or_else(|| {
            ErrorCode::Internal(format!("clone descendant {table_id} has no observed LVT"))
        })?;
        let table = catalog.get_table_by_info(&table_info)?;
        let descendant = FuseTable::try_from_table(table.as_ref())?;
        let mut candidate = lvt
            .map(LeastVisibleTime::new)
            .unwrap_or_else(LeastVisibleTime::unbounded);
        let segments = if let Some(location) = descendant.snapshot_loc() {
            let version = TableMetaLocationGenerator::snapshot_version(&location);
            let head = descendant
                .read_table_snapshot()
                .await?
                .ok_or_else(|| ErrorCode::StorageNotFound("clone head disappeared during mark"))?;
            let head_time = head
                .timestamp
                .ok_or_else(|| ErrorCode::Internal("clone head has no timestamp"))?;
            let (boundary, limit) = match mode {
                CloneDescendantMarkMode::Vacuum => {
                    // A VACUUM target may advance descendant fences, but its session retention
                    // settings must not shorten another table's history.
                    match descendant.get_clone_descendant_retention_policy(ctx.as_ref())? {
                        RetentionPolicy::ByTimePeriod(period) => {
                            let cutoff = retention_cutoff(scan_time, head_time, period);
                            (Some(lvt.map_or(cutoff, |time| time.max(cutoff))), None)
                        }
                        RetentionPolicy::ByNumOfSnapshotsToKeep(n) => (lvt, Some(n)),
                    }
                }
                CloneDescendantMarkMode::ReferenceOnly => {
                    // Derived-file cleanup does not atomically publish LVTs. Preserve every
                    // descendant snapshot that could still be published.
                    (lvt, None)
                }
            };
            let mut protected = HashSet::new();
            let mut is_head = true;
            let (root, _) = descendant
                .select_snapshot_history_gc_root(
                    &ctx,
                    (head, version),
                    boundary,
                    limit,
                    |snapshot| {
                        // VACUUM marks retention-bounded history and publishes its LVT.
                        // Reference-only cleanup always includes the live head and every snapshot
                        // at or above the existing LVT.
                        if mode.advances_lvt()
                            || is_head
                            || lvt.is_none_or(|lvt| snapshot.timestamp.is_some_and(|ts| ts >= lvt))
                        {
                            protected.extend(snapshot.segments.iter().cloned());
                        }
                        is_head = false;
                    },
                )
                .await?;
            if mode.advances_lvt() {
                let root_timestamp = root.timestamp.ok_or_else(|| {
                    ErrorCode::Internal(format!(
                        "clone descendant {table_id} GC root has no timestamp"
                    ))
                })?;
                candidate.time = candidate.time.max(root_timestamp);
            }
            protected
        } else {
            let statistics = &table_info.meta.statistics;
            if statistics.number_of_rows != 0
                || statistics.data_bytes != 0
                || statistics.compressed_data_bytes != 0
                || statistics.number_of_segments.unwrap_or(0) != 0
                || statistics.number_of_blocks.unwrap_or(0) != 0
            {
                return Err(ErrorCode::Internal(format!(
                    "non-empty clone descendant {table_id} has no snapshot location"
                )));
            }
            HashSet::new()
        };
        Ok((
            table_id,
            lvt_seq,
            candidate,
            segments,
            CloneDescendantTagSource {
                table_id,
                operator: descendant.get_operator(),
            },
        ))
    }

    /// Collect descendant references without advancing LVTs. This is only for derived-file
    /// cleanup, whose mark is not followed by an atomic fence publication.
    async fn mark_clone_descendant_references<T>(
        &self,
        ctx: Arc<dyn TableContext>,
        catalog: &Arc<dyn Catalog>,
        segments: &mut HashSet<Location>,
        mode: CloneDescendantMarkMode,
        concurrency: &VacuumConcurrency,
        status_callback: T,
    ) -> Result<CloneDescendantMark>
    where
        T: Fn(String),
    {
        let clone_group_id = self.clone_group_id()?;
        let bindings = concurrency
            .run(catalog.list_clone_group_bindings(clone_group_id))
            .await?;
        let descendant_ids = Self::clone_descendant_ids(clone_group_id, self.get_id(), &bindings)?;
        if descendant_ids.is_empty() {
            return Ok(CloneDescendantMark::default());
        }
        let table_ids = descendant_ids.iter().copied().collect::<Vec<_>>();
        let tenant = ctx.get_tenant();
        // Observe LVTs before the batched head read. Preserve those sequences through publication.
        let observed_lvts = stream::iter(table_ids.iter().copied().map(|table_id| {
            let catalog = catalog.clone();
            let tenant = tenant.clone();
            concurrency.run(async move {
                let lvt = catalog
                    .get_table_lvt(&LeastVisibleTimeIdent::new(&tenant, table_id))
                    .await?;
                let (seq, lvt) = lvt
                    .map(|v| (v.seq, (!v.data.is_unbounded()).then_some(v.data.time)))
                    .unwrap_or((0, None));
                Ok((table_id, (seq, lvt)))
            })
        }))
        .buffer_unordered(concurrency.limit)
        .try_collect::<HashMap<_, _>>()
        .await?;
        let descendants = concurrency
            .run(catalog.mget_table_metas_by_ids(&table_ids))
            .await?;
        let scan_time = Utc::now();
        if descendants.iter().any(|(_, meta)| meta.is_none()) {
            // One recheck for the whole batch: final GC atomically removes metadata and binding.
            let current_bindings = concurrency
                .run(catalog.list_clone_group_bindings(clone_group_id))
                .await?;
            if let Some(id) = Self::bound_descendant_missing_meta(&descendants, &current_bindings) {
                return Err(ErrorCode::StorageNotFound(format!(
                    "clone descendant {id} metadata is unavailable; defer GC"
                )));
            }
        }
        let mut scans = stream::iter(descendants.into_iter().filter_map(|(id, meta)| {
            meta.map(|seq_meta| {
                let mut table_info = self.get_table_info().clone();
                table_info.ident.table_id = id;
                table_info.ident.seq = seq_meta.seq;
                table_info.meta = seq_meta.data;
                let observed_lvt = observed_lvts.get(&id).copied();
                concurrency.run(Self::mark_one_clone_descendant(
                    ctx.clone(),
                    catalog.clone(),
                    table_info,
                    observed_lvt,
                    scan_time,
                    mode,
                ))
            })
        }))
        .buffer_unordered(concurrency.limit);
        let mut mark = CloneDescendantMark {
            descendant_ids,
            ..Default::default()
        };
        while let Some((table_id, seq, candidate, protected, tag_source)) = scans.try_next().await?
        {
            if mode.advances_lvt() {
                mark.lvt_updates.push((table_id, seq, candidate));
            }
            status_callback(format!(
                "gc clone refs: table {table_id}, protected segments: {}",
                protected.len()
            ));
            segments.extend(protected);
            mark.tag_sources.push(tag_source);
        }
        Ok(mark)
    }

    /// Re-read lineage before sweeping and stop if new descendants need an additional mark.
    /// Existing descendants are protected by either published retention fences (VACUUM) or the
    /// full publishable history scan used by reference-only derived-file cleanup.
    pub async fn has_new_clone_descendants(
        &self,
        catalog: &Arc<dyn Catalog>,
        observed_descendants: &HashSet<u64>,
    ) -> Result<bool> {
        let clone_group_id = self.clone_group_id()?;
        let bindings = catalog.list_clone_group_bindings(clone_group_id).await?;
        let current_descendants =
            Self::clone_descendant_ids(clone_group_id, self.get_id(), &bindings)?;
        Ok(!current_descendants.is_subset(observed_descendants))
    }

    pub async fn extend_clone_descendant_tag_segments(
        catalog: &Arc<dyn Catalog>,
        tag_sources: &[CloneDescendantTagSource],
        segments: &mut HashSet<Location>,
    ) -> Result<()> {
        for source in tag_sources {
            Self::protect_table_tags(source.table_id, &source.operator, catalog, segments).await?;
        }
        Ok(())
    }

    /// Get all segments still reachable from this table and its clone descendants.
    #[async_backtrace::framed]
    pub async fn get_snapshot_referenced_segments<T>(
        &self,
        ctx: Arc<dyn TableContext>,
        status_callback: T,
    ) -> Result<Option<HashSet<Location>>>
    where
        T: Fn(String),
    {
        let Some(root_snapshot_location) = self.snapshot_loc() else {
            return Ok(None);
        };
        let version = TableMetaLocationGenerator::snapshot_version(&root_snapshot_location);
        let head = self.read_table_snapshot().await?.ok_or_else(|| {
            ErrorCode::StorageNotFound("table head disappeared while collecting references")
        })?;
        let timestamp = head.timestamp.ok_or_else(|| {
            ErrorCode::Internal(format!("table {} head has no timestamp", self.get_id()))
        })?;
        let (boundary, limit) = match self.get_data_retention_policy(ctx.as_ref())? {
            RetentionPolicy::ByTimePeriod(period) => (Some(timestamp - period), None),
            RetentionPolicy::ByNumOfSnapshotsToKeep(limit) => (None, Some(limit)),
        };
        let mut segments = HashSet::new();
        self.select_snapshot_history_gc_root(&ctx, (head, version), boundary, limit, |snapshot| {
            segments.extend(snapshot.segments.iter().cloned())
        })
        .await?;

        let catalog = ctx.get_catalog(self.get_table_info().catalog()).await?;
        Self::protect_table_tags(
            self.get_id(),
            self.get_operator_ref(),
            &catalog,
            &mut segments,
        )
        .await?;
        let concurrency =
            VacuumConcurrency::new(ctx.get_settings().get_max_vacuum_threads()? as usize);
        let mark = self
            .mark_clone_descendant_references(
                ctx.clone(),
                &catalog,
                &mut segments,
                CloneDescendantMarkMode::ReferenceOnly,
                &concurrency,
                status_callback,
            )
            .await?;
        Self::extend_clone_descendant_tag_segments(&catalog, &mark.tag_sources, &mut segments)
            .await?;
        Ok(Some(segments))
    }

    /// Prepare owner GC using the LVT observed before refreshing the table's head.
    /// An absent LVT is represented by unbounded(); this method never re-reads it.
    pub async fn prepare_snapshot_gc_selection(
        &self,
        ctx: &Arc<dyn TableContext>,
        respect_flash_back: bool,
        observed_lvt: &LeastVisibleTime,
    ) -> Result<Option<SnapshotGcSelection>> {
        let Some(latest_snapshot) = self.read_table_snapshot().await? else {
            info!(
                "Table {} has no snapshot, stopping vacuum",
                self.table_info.desc
            );
            return Ok(None);
        };
        let latest_location = self.snapshot_loc().ok_or_else(|| {
            ErrorCode::Internal(format!(
                "table {} has a snapshot but no snapshot location",
                self.get_id()
            ))
        })?;
        let start = Instant::now();
        let retention_policy = self.get_data_retention_policy(ctx.as_ref())?;
        let snapshot_location_prefix = self.meta_location_generator().snapshot_location_prefix();

        let mut is_vacuum_all = false;
        let mut respect_flash_back_with_lvt = None;

        let snapshots_before_lvt = match retention_policy {
            RetentionPolicy::ByTimePeriod(delta_duration) => {
                info!("Using ByTimePeriod policy {:?}", delta_duration);
                let retention_period = if self.is_transient() {
                    // For transient table, keep no history data
                    TimeDelta::zero()
                } else {
                    delta_duration
                };

                // A zero retention period indicates that we should vacuum all the historical snapshots
                is_vacuum_all = retention_period.is_zero();

                if !is_uuid_v7(&latest_snapshot.snapshot_id) {
                    return Ok(None);
                }
                let timestamp = latest_snapshot
                    .timestamp
                    .ok_or_else(|| ErrorCode::Internal("GC head has no timestamp"))?;
                let lvt = max(
                    retention_cutoff(Utc::now(), timestamp, retention_period),
                    observed_lvt.time,
                );

                respect_flash_back_with_lvt = respect_flash_back.then_some(lvt);

                ctx.set_status_info(&format!(
                    "Calculated LVT for table {}, elapsed: {:?}, LVT: {:?}",
                    self.table_info.desc,
                    start.elapsed(),
                    lvt
                ));

                if is_vacuum_all {
                    self.list_files_until_prefix(
                        snapshot_location_prefix,
                        &latest_location,
                        true,
                        None,
                    )
                    .await?
                } else {
                    self.list_files_until_timestamp(snapshot_location_prefix, lvt, true, None)
                        .await?
                }
            }
            RetentionPolicy::ByNumOfSnapshotsToKeep(num_snapshots_to_keep) => {
                info!(
                    "Using ByNumOfSnapshotsToKeep policy {:?}",
                    num_snapshots_to_keep
                );
                // List the snapshot order by timestamp asc, till the current snapshot(inclusively).
                let need_one_more = true;
                let mut snapshots = self
                    .list_files_until_prefix(
                        snapshot_location_prefix,
                        &latest_location,
                        need_one_more,
                        None,
                    )
                    .await?;
                let len = snapshots.len();
                if len <= num_snapshots_to_keep {
                    // Only the current snapshot is there, done
                    return Ok(None);
                }
                if num_snapshots_to_keep == 1 {
                    // Expecting only one snapshot left, which means that we can use the current snapshot
                    // as gc root, this flag will be propagated to the select_gc_root func later.
                    is_vacuum_all = true;
                }

                // When selecting the GC root later, the last snapshot in `snapshots` (after truncation)
                // is the candidate, but its commit status is uncertain, so its previous snapshot is used
                // as the GC root instead (except in the is_vacuum_all case).

                // Therefore, during snapshot truncation, we keep 2 extra snapshots;
                // see `select_gc_root` for details.
                let num_candidates = len - num_snapshots_to_keep + 2;
                snapshots.truncate(num_candidates);
                snapshots
            }
        };

        let elapsed = start.elapsed();
        ctx.set_status_info(&format!(
            "Listed snapshots for table {}, elapsed: {:?}, snapshots_dir: {:?}, snapshots: {:?}",
            self.table_info.desc,
            elapsed,
            snapshot_location_prefix,
            slice_summary(&snapshots_before_lvt)
        ));

        let Some(selection) = self
            .select_gc_root(
                ctx,
                latest_location,
                &snapshots_before_lvt,
                is_vacuum_all,
                respect_flash_back_with_lvt,
                latest_snapshot,
            )
            .await?
        else {
            return Ok(None);
        };

        ctx.set_status_info(&format!(
            "Selected gc_root for table {}, elapsed: {:?}, gc_root: {:?}, snapshots_to_gc: {:?}",
            self.table_info.desc,
            start.elapsed(),
            selection.gc_root,
            slice_summary(&selection.snapshots_to_gc)
        ));
        Ok(Some(selection))
    }

    async fn select_gc_root(
        &self,
        ctx: &Arc<dyn TableContext>,
        latest_location: String,
        snapshots_before_lvt: &[Entry],
        is_vacuum_all: bool,
        respect_flash_back: Option<DateTime<Utc>>,
        latest_snapshot: Arc<TableSnapshot>,
    ) -> Result<Option<SnapshotGcSelection>> {
        let op = self.get_operator();
        let version = TableMetaLocationGenerator::snapshot_version(&latest_location);
        let (gc_root_path, selected_root) = if is_vacuum_all {
            (latest_location, Some((latest_snapshot, version)))
        } else if let Some(lvt) = respect_flash_back {
            let (root, version) = self
                .select_snapshot_history_gc_root(
                    ctx,
                    (latest_snapshot, version),
                    Some(lvt),
                    None,
                    |_| {},
                )
                .await?;
            // An intact chain may end at an anchor newer than the cutoff. It must still be
            // protected, but there is no owner history at the requested cutoff to reclaim.
            if root.timestamp.is_none_or(|timestamp| timestamp > lvt) {
                return Ok(None);
            }
            let location = self
                .meta_location_generator()
                .gen_snapshot_location(&root.snapshot_id, version)?;
            (location, Some((root, version)))
        } else {
            let Some(anchor_entry) = snapshots_before_lvt.last() else {
                info!("no snapshots before lvt, stop vacuuming");
                return Ok(None);
            };
            let (anchor, _) =
                SnapshotsIO::read_snapshot(anchor_entry.path().to_owned(), op.clone(), false)
                    .await?;
            let Some((gc_root_id, gc_root_ver)) = anchor.prev_snapshot_id else {
                info!("anchor has no prev_snapshot_id, stop vacuuming");
                return Ok(None);
            };
            let gc_root_path = self
                .meta_location_generator()
                .gen_snapshot_location(&gc_root_id, gc_root_ver)?;
            if !is_uuid_v7(&gc_root_id) {
                info!("gc_root {} is not v7", gc_root_path);
                return Ok(None);
            }
            (gc_root_path, None)
        };

        let dal = self.get_operator_ref();
        let gc_root = match selected_root {
            Some(root) => Ok(root),
            None => SnapshotsIO::read_snapshot(gc_root_path.clone(), op.clone(), false).await,
        };
        let gc_root_meta_ts = match dal.stat(&gc_root_path).await {
            Ok(v) => v.last_modified().ok_or_else(|| {
                ErrorCode::StorageOther(format!(
                    "Failed to get `last_modified` metadata of the gc root object '{}'",
                    gc_root_path
                ))
            })?,
            Err(e) => {
                return if e.kind() == ErrorKind::NotFound {
                    // Concurrent vacuum, ignore it
                    Ok(None)
                } else {
                    Err(e.into())
                };
            }
        };
        let gc_root_meta_ts = DateTime::<Utc>::from(SystemTime::from(gc_root_meta_ts));

        match gc_root {
            Ok((gc_root, _)) => {
                info!("gc_root found: {:?}", gc_root);
                let mut gc_candidates = Vec::with_capacity(snapshots_before_lvt.len());

                for snapshot in snapshots_before_lvt.iter() {
                    let path = snapshot.path();
                    let last_part = path.rsplit('/').next().unwrap();
                    if last_part.starts_with(VACUUM2_OBJECT_KEY_PREFIX) {
                        gc_candidates.push(path.to_owned());
                    } else {
                        // This snapshot is created by a node of the previous version which does not
                        // support vacuum2, we rely on the `ASSUMPTION_MAX_TXN_DURATION` to identify if
                        // it is available to be vacuumed.
                        let last_modified = match snapshot.metadata().last_modified() {
                            None => dal.stat(path).await?.last_modified().ok_or_else(|| {
                                ErrorCode::StorageOther(format!(
                                    "Failed to get `last_modified` metadata of the snapshot object '{}'",
                                    gc_root_path
                                ))
                            })?,
                            Some(v) => v,
                        };
                        let last_modified = DateTime::<Utc>::from(SystemTime::from(last_modified));
                        if last_modified + ASSUMPTION_MAX_TXN_DURATION < gc_root_meta_ts {
                            gc_candidates.push(path.to_owned());
                        }
                    }
                }

                let gc_root_idx = gc_candidates.binary_search(&gc_root_path).map_err(|_| {
                    ErrorCode::Internal(format!(
                        "gc root path {} should be one of the candidates, candidates: {:?}",
                        gc_root_path, gc_candidates
                    ))
                })?;
                let snapshots_to_gc = gc_candidates[..gc_root_idx].to_vec();
                let timestamp = gc_root.timestamp.ok_or_else(|| {
                    ErrorCode::Internal(format!("GC root {} has no timestamp", gc_root_path))
                })?;
                let lvt = LeastVisibleTime::new(timestamp);
                Ok(Some(SnapshotGcSelection {
                    gc_root,
                    snapshots_to_gc,
                    gc_root_meta_ts,
                    gc_root_path,
                    lvt,
                }))
            }
            Err(e) => {
                info!("read gc_root {} failed: {:?}", gc_root_path, e);
                Ok(None)
            }
        }
    }
}

pub async fn vacuum_tables_from_info(
    table_infos: Vec<TableInfo>,
    ctx: Arc<dyn TableContext>,
    vacuum_handler: Arc<VacuumHandlerWrapper>,
) -> Result<()> {
    for table_info in table_infos {
        let table = FuseTable::create_without_refresh_table_info(
            table_info,
            ctx.get_settings().get_s3_storage_class()?,
        )?
        .refresh(ctx.as_ref())
        .await?;
        let fuse_table = FuseTable::try_from_table(table.as_ref())?;
        fuse_table
            .vacuum_table(ctx.clone(), &vacuum_handler, true)
            .await;
    }

    Ok(())
}

pub fn slice_summary<T: std::fmt::Debug>(s: &[T]) -> String {
    if s.len() > 10 {
        let first_five = &s[..5];
        let last_five = &s[s.len() - 5..];
        format!(
            "First five: {:?}, Last five: {:?},Len: {}",
            first_five,
            last_five,
            s.len()
        )
    } else {
        format!("{:?}", s)
    }
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::AtomicUsize;
    use std::sync::atomic::Ordering;

    use chrono::TimeZone;
    use futures_util::FutureExt;
    use tokio::sync::oneshot;

    use super::*;

    #[tokio::test]
    async fn test_vacuum_concurrency_budget_and_cancellation() {
        struct ActiveScan<'a>(&'a AtomicUsize);
        impl Drop for ActiveScan<'_> {
            fn drop(&mut self) {
                self.0.fetch_sub(1, Ordering::SeqCst);
            }
        }

        // Three jobs represent owner selection plus two descendant scans. Polling and channels
        // make overlap, the upper bound and cancellation observable without timing assumptions.
        for limit in 1..=3 {
            let budget = VacuumConcurrency::new(limit);
            let active = AtomicUsize::new(0);
            let peak = AtomicUsize::new(0);
            let work = |done: oneshot::Receiver<Result<()>>| async {
                let count = active.fetch_add(1, Ordering::SeqCst) + 1;
                peak.fetch_max(count, Ordering::SeqCst);
                let _active = ActiveScan(&active);
                done.await.unwrap()
            };
            let (owner_done, owner_wait) = oneshot::channel();
            let (first_done, first_wait) = oneshot::channel();
            let (second_done, second_wait) = oneshot::channel();
            let mut owner = budget.run(work(owner_wait)).boxed();
            let mut first = budget.run(work(first_wait)).boxed();
            let mut second = budget.run(work(second_wait)).boxed();
            assert!(futures_util::poll!(&mut owner).is_pending());
            assert!(futures_util::poll!(&mut first).is_pending());
            assert!(futures_util::poll!(&mut second).is_pending());
            assert_eq!(active.load(Ordering::SeqCst), limit);

            owner_done.send(Ok(())).unwrap();
            owner.await.unwrap();
            assert!(futures_util::poll!(&mut first).is_pending());
            assert!(futures_util::poll!(&mut second).is_pending());
            assert_eq!(active.load(Ordering::SeqCst), limit.min(2));
            first_done
                .send(Err(ErrorCode::StorageNotFound("incomplete mark")))
                .unwrap();
            assert_eq!(
                first.await.unwrap_err().code(),
                ErrorCode::STORAGE_NOT_FOUND
            );
            // The coordinator drops outstanding work rather than publishing a partial mark.
            drop(second);
            drop(second_done);
            assert_eq!(active.load(Ordering::SeqCst), 0);
            assert_eq!(peak.load(Ordering::SeqCst), limit);
            assert_eq!(budget.permits.available_permits(), limit);
        }
    }

    #[test]
    fn test_retention_cutoff_is_bounded_by_latest_snapshot() {
        let now = Utc.with_ymd_and_hms(2025, 1, 10, 12, 0, 0).unwrap();
        let retention_period = TimeDelta::days(2);

        // When the latest snapshot is newer than the retention boundary, use
        // now - retention as the cutoff.
        let latest_after_cutoff = Utc.with_ymd_and_hms(2025, 1, 9, 12, 0, 0).unwrap();
        assert_eq!(
            retention_cutoff(now, latest_after_cutoff, retention_period),
            Utc.with_ymd_and_hms(2025, 1, 8, 12, 0, 0).unwrap()
        );

        // The cutoff must not move past the latest snapshot. This also keeps
        // the result valid when the host clock is ahead of snapshot time.
        let latest_before_cutoff = Utc.with_ymd_and_hms(2025, 1, 7, 12, 0, 0).unwrap();
        assert_eq!(
            retention_cutoff(now, latest_before_cutoff, retention_period),
            latest_before_cutoff
        );
    }

    #[test]
    fn test_clone_descendant_ids_detects_new_descendant() {
        let initial = vec![(2, 1), (3, 2), (4, 1)];
        assert_eq!(
            FuseTable::clone_descendant_ids(1, 1, &initial).unwrap(),
            HashSet::from([2, 3, 4])
        );
        let observed = FuseTable::clone_descendant_ids(1, 2, &initial).unwrap();
        assert_eq!(observed, HashSet::from([3]));

        let mut changed = initial;
        changed.push((5, 3));
        let current = FuseTable::clone_descendant_ids(1, 2, &changed).unwrap();
        assert_eq!(current, HashSet::from([3, 5]));
        assert!(!current.is_subset(&observed));
    }

    #[test]
    fn test_clone_descendant_ids_rejects_disconnected_lineage() {
        let err = FuseTable::clone_descendant_ids(1, 1, &[(2, 1), (4, 3)]).unwrap_err();
        assert_eq!(err.code(), ErrorCode::INTERNAL);

        let err = FuseTable::clone_descendant_ids(1, 3, &[(2, 1)]).unwrap_err();
        assert_eq!(err.code(), ErrorCode::INTERNAL);
    }

    #[test]
    fn test_clone_descendant_ids_rejects_cyclic_lineage() {
        // Table 2 has two direct sources, which keeps the 2 -> 3 -> 2 cycle reachable from the
        // group root. Every owner perspective must fail closed rather than treat itself as its
        // own descendant and advance its LVT past its own GC root.
        let cyclic = [(2, 1), (3, 2), (2, 3)];
        for owner in [1, 2, 3] {
            let err = FuseTable::clone_descendant_ids(1, owner, &cyclic).unwrap_err();
            assert_eq!(err.code(), ErrorCode::INTERNAL);
        }
    }
}
