SELECT SOUNDEX(NULL);
SELECT SOUNDEX('Hello');
SELECT SOUNDEX('hello');
SELECT SOUNDEX('Quadratically');
SELECT SOUNDEX('quadratically');
SELECT SOUNDEX('你好中国');
SELECT SOUNDEX('你好中国北京');
SELECT SOUNDEX('');
SELECT SOUNDEX('he');
SELECT SOUNDEX('hello all folks');
SELECT SOUNDEX('#3556 in bugdb');
SELECT SOUNDEX('####');
SELECT SOUNDEX('##🐑hello');
SELECT SOUNDEX('##🐑🐑he🐑llo🐑');
SELECT SOUNDEX('🐑he🐑llo🐑');
SELECT SOUNDEX('teacher');
SELECT SOUNDEX('TEACHER');
SELECT SOUNDEX('much');
SELECT SOUNDEX('MUCH');
SELECT SOUNDEX('1.23');
SELECT SOUNDEX('pneumonoultramicroscopicsilicovolcanoconiosis');
SELECT SOUNDEX('pneumonoultramicroscopicsilicovolcanoconiosis hello world');
