SELECT '=== LPAD null ===';
SELECT LPAD(NULL, NULL, NULL);
SELECT LPAD('a', NULL, NULL);
SELECT LPAD(NULL, 1, NULL);
SELECT LPAD('a', 1, NULL);
SELECT LPAD(NULL, NULL, 'b');
SELECT LPAD('a', NULL, 'b');
SELECT LPAD(NULL, 1, 'b');

SELECT '=== LPAD const, const, const ===';
SELECT LPAD('', 0, '');
SELECT LPAD('', 10, 'abcde');
SELECT LPAD('12345', 0, '');
SELECT LPAD('12345', 0, 'a');
SELECT LPAD('12345', 1, 'a');
SELECT LPAD('12345', 10, 'a');
SELECT LPAD('12345', 10, 'abc');
SELECT LPAD('12345', 10, 'abcde');

SELECT '=== LPAD series, const, const ===';
SELECT LPAD(toString(number), 3, 'a') FROM numbers(5) ORDER BY number;
SELECT '=== LPAD const, series, const ===';
SELECT LPAD('1', number, 'a') FROM numbers(5) ORDER BY number;
SELECT '=== LPAD series, series, const ===';
SELECT LPAD(toString(number), number, 'a') FROM numbers(5) ORDER BY number;
SELECT '=== LPAD const, const, series ===';
SELECT LPAD('1', 3, toString(number)) FROM numbers(5) ORDER BY number;
SELECT '=== LPAD series, const, series ===';
SELECT LPAD(toString(number), 3, toString(number)) FROM numbers(5) ORDER BY number;
SELECT '=== LPAD const, series, series ===';
SELECT LPAD('1', number, toString(number)) FROM numbers(5) ORDER BY number;
SELECT '=== LPAD series, series, series ===';
SELECT LPAD(toString(number), number, toString(number)) FROM numbers(5) ORDER BY number;

SELECT '=== RPAD null ===';
SELECT RPAD(NULL, NULL, NULL);
SELECT RPAD('a', NULL, NULL);
SELECT RPAD(NULL, 1, NULL);
SELECT RPAD('a', 1, NULL);
SELECT RPAD(NULL, NULL, 'b');
SELECT RPAD('a', NULL, 'b');
SELECT RPAD(NULL, 1, 'b');

SELECT '=== RPAD const, const, const ===';
SELECT RPAD('', 0, '');
SELECT RPAD('', 10, 'abcde');
SELECT RPAD('12345', 0, '');
SELECT RPAD('12345', 0, 'a');
SELECT RPAD('12345', 1, 'a');
SELECT RPAD('12345', 10, 'a');
SELECT RPAD('12345', 10, 'abc');
SELECT RPAD('12345', 10, 'abcde');

SELECT '=== RPAD series, const, const ===';
SELECT RPAD(toString(number), 3, 'a') FROM numbers(5) ORDER BY number;
SELECT '=== RPAD const, series, const ===';
SELECT RPAD('1', number, 'a') FROM numbers(5) ORDER BY number;
SELECT '=== RPAD series, series, const ===';
SELECT RPAD(toString(number), number, 'a') FROM numbers(5) ORDER BY number;
SELECT '=== RPAD const, const, series ===';
SELECT RPAD('1', 3, toString(number)) FROM numbers(5) ORDER BY number;
SELECT '=== RPAD series, const, series ===';
SELECT RPAD(toString(number), 3, toString(number)) FROM numbers(5) ORDER BY number;
SELECT '=== RPAD const, series, series ===';
SELECT RPAD('1', number, toString(number)) FROM numbers(5) ORDER BY number;
SELECT '=== RPAD series, series, series ===';
SELECT RPAD(toString(number), number, toString(number)) FROM numbers(5) ORDER BY number;
