// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::sync::Arc;

use databend_common_catalog::table_context::TableContext;
use databend_common_exception::Result;
use databend_common_expression::DataBlock;
use databend_common_pipeline_core::processors::OutputPort;
use databend_common_pipeline_core::processors::ProcessorPtr;
use databend_common_pipeline_sources::AsyncSource;
use databend_common_pipeline_sources::AsyncSourcer;
use databend_common_sql::executor::physical_plans::UnionAll;
use futures_util::TryStreamExt;
use poem::web::Data;

use crate::pipelines::executor::ExecutorSettings;
use crate::pipelines::executor::PipelinePullingExecutor;
use crate::schedulers::build_query_pipeline;
use crate::schedulers::build_query_pipeline_without_render_result_set;
use crate::sessions::QueryContext;
use crate::stream::PullingExecutorStream;

// The whole recursive cte as source.
pub struct TransformRecursiveCteSource {
    ctx: Arc<QueryContext>,
    union_plan: UnionAll,
    output_data: Option<DataBlock>,
    executor: Option<PullingExecutorStream>,
    finished: bool,
    recursive_step: usize,
    rows_in_recursive: usize,
    cte_name: String,
    // Save the data that generated by each recursive step
    intermediate_data: Vec<DataBlock>,
}

impl TransformRecursiveCteSource {
    pub fn try_create(
        ctx: Arc<QueryContext>,
        output_port: Arc<OutputPort>,
        union_plan: UnionAll,
    ) -> Result<ProcessorPtr> {
        let cte_name = union_plan.cte_name.as_ref().unwrap().clone();
        AsyncSourcer::create(ctx.clone(), output_port, TransformRecursiveCteSource {
            ctx,
            union_plan,
            output_data: None,
            executor: None,
            finished: false,
            recursive_step: 0,
            rows_in_recursive: 0,
            cte_name,
            intermediate_data: vec![],
        })
    }

    async fn build_union(&mut self) -> Result<()> {
        let plan = if self.recursive_step == 0 {
            self.union_plan.left.clone()
        } else {
            self.union_plan.right.clone()
        };
        self.recursive_step += 1;
        let build_res = build_query_pipeline_without_render_result_set(&self.ctx, &plan).await?;
        let settings = ExecutorSettings::try_create(self.ctx.clone())?;
        let pulling_executor = PipelinePullingExecutor::from_pipelines(build_res, settings)?;
        self.ctx.set_executor(pulling_executor.get_inner())?;
        self.executor = Some(PullingExecutorStream::create(pulling_executor)?);
        Ok(())
    }
}

#[async_trait::async_trait]
impl AsyncSource for TransformRecursiveCteSource {
    const NAME: &'static str = "TransformRecursiveCteSource";

    #[async_trait::unboxed_simple]
    #[async_backtrace::framed]
    async fn generate(&mut self) -> Result<Option<DataBlock>> {
        let mut res = None;
        if !self.finished {
            if self.executor.is_none() {
                self.build_union().await?;
            }
            // Todo: improve here to make it streaming.
            let data = DataBlock::concat(
                &self
                    .executor
                    .take()
                    .unwrap()
                    .try_collect::<Vec<DataBlock>>()
                    .await?,
            )?;

            let row_size = data.num_rows();
            self.rows_in_recursive += row_size;
            if row_size > 0 {
                // Prepare the data of next round recursive.
                self.ctx
                    .update_recursive_cte_scan(&self.cte_name, vec![data.clone()])?;
                res = Some(data);
            } else {
                self.finished = true;
            }
        }
        Ok(res)
    }
}
