name: "Test compat client"
description: "Running client compat tests in cluster mode"
inputs:
  nox_session:
    description: "nox session to run"
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_test
      with:
        artifacts: meta,query

    - uses: ./.github/actions/setup_minio

    - uses: wntrblm/nox@2025.05.01

    - uses: actions/setup-java@v4
      if: ${{ inputs.nox_session == 'java_client' }}
      with:
        distribution: temurin
        java-version: "17"

    - name: Set up Maven
      if: ${{ inputs.nox_session == 'java_client' }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9

    - name: Setup Go
      if: ${{ inputs.nox_session == 'go_client' }}
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Run databend with Cluster mode
      shell: bash
      env:
        STORAGE_ALLOW_INSECURE: true
      run: bash ./scripts/ci/deploy/databend-query-cluster-3-nodes-nginx.sh

    - name: Run python client compat tests
      if: ${{ inputs.nox_session == 'python_client' }}
      shell: bash
      run: nox -f tests/nox/noxfile.py -s python_client

    - name: Run java client compat tests
      if: ${{ inputs.nox_session == 'java_client' }}
      shell: bash
      run: nox -f tests/nox/noxfile.py -s java_client

    - name: Run go client compat tests
      if: ${{ inputs.nox_session == 'go_client' }}
      shell: bash
      run: nox -f tests/nox/noxfile.py -s go_client
      env:
        DATABEND_GO_SKIP_UP: "1"
