// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::num::ParseIntError;

use databend_meta_client::kvapi;

use crate::tenant::ToTenant;
use crate::tenant_key::ident::TIdent;

#[derive(Debug, Clone, PartialEq, Eq, Hash, kvapi::KeyCodec)]
pub struct TableIdRevisionV2 {
    table_id: u64,
    revision: String,
}

/// The v2 identifier of a Table lock.
///
/// The revision segment is formatted as the suffix generated by PutSequential.
pub type TableLockIdentV2 = TIdent<Resource, TableIdRevisionV2>;

pub use kvapi_impl::Resource;

pub const TABLE_LOCK_SEQ_KEY_V2: &str = "__fd_table_lock_v2_seq";

impl TableLockIdentV2 {
    pub fn new(tenant: impl ToTenant, table_id: u64, revision: u64) -> Self {
        Self::new_generic(tenant, TableIdRevisionV2 {
            table_id,
            revision: format_table_lock_revision_v2(revision),
        })
    }

    pub fn table_id(&self) -> u64 {
        self.name().table_id
    }

    pub fn revision(&self) -> u64 {
        self.try_revision()
            .expect("table lock v2 revision must be generated by PutSequential")
    }

    pub fn try_revision(&self) -> Result<u64, ParseIntError> {
        self.name().revision.replace('_', "").parse()
    }
}

pub fn format_table_lock_revision_v2(revision: u64) -> String {
    format!("{:021}", revision)
        .chars()
        .enumerate()
        .fold(String::new(), |mut acc, (i, c)| {
            if i > 0 && i % 3 == 0 {
                acc.push('_');
            }
            acc.push(c);
            acc
        })
}

mod kvapi_impl {
    use crate::schema::LockMeta;
    use crate::tenant_key::resource::TenantResource;

    pub struct Resource;
    impl TenantResource for Resource {
        const PREFIX: &'static str = "__fd_table_lock_v2";
        const TYPE: &'static str = "TableLockIdentV2";
        const HAS_TENANT: bool = true;
        type ValueType = LockMeta;
    }
}

#[cfg(test)]
mod tests {
    use databend_meta_client::kvapi::testing::assert_round_trip;

    use super::TableLockIdentV2;
    use crate::tenant::Tenant;

    #[test]
    fn test_table_lock_ident_v2() {
        let tenant = Tenant::new_literal("test");
        let ident = TableLockIdentV2::new(tenant, 5, 6);
        assert_round_trip(
            ident,
            "__fd_table_lock_v2/test/5/000_000_000_000_000_000_006",
        );
    }
}
