CREATE TABLE IF NOT EXISTS random_table (i INT, ni INT NULL, f FLOAT, b BOOLEAN, s VARCHAR, d DATE, t TIMESTAMP, a ARRAY(INT)) ENGINE=RANDOM;
SELECT COUNT(*) FROM (SELECT * FROM random_table LIMIT 5);
SELECT COUNT(*) FROM (SELECT * FROM random_table LIMIT 10);
SELECT COUNT(*) FROM (SELECT * FROM random_table LIMIT 10000);
SELECT COUNT(*) FROM (SELECT * FROM random_table LIMIT 60000);
SELECT COUNT(*) FROM (SELECT * FROM random_table LIMIT 87654);
SELECT COUNT(*) FROM random_table;
DROP TABLE random_table;