CREATE FUNCTION IF NOT EXISTS isnotempty AS(p) -> not(is_null(p));
SELECT '==TEST SHOW USER FUNCTIONS==';
SHOW USER FUNCTIONS;
SELECT '==TEST SELECT * FROM SYSTEM.USER_FUNCTIONS==';
SELECT * FROM system.user_functions;
DROP FUNCTION IF EXISTS isnotempty;