# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresource.proto\x12\rresourceproto\"4\n\x14\x41pplyResourceRequest\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06script\x18\x04 \x01(\t\"\x9d\x01\n\x15\x41pplyResourceResponse\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x42\n\x07headers\x18\x02 \x03(\x0b\x32\x31.resourceproto.ApplyResourceResponse.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32m\n\x0fResourceService\x12Z\n\rApplyResource\x12#.resourceproto.ApplyResourceRequest\x1a$.resourceproto.ApplyResourceResponseB!Z\x1f\x64\x61tabend.com/cloudcontrol/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037databend.com/cloudcontrol/proto'
  _globals['_APPLYRESOURCERESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_APPLYRESOURCERESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_APPLYRESOURCEREQUEST']._serialized_start=33
  _globals['_APPLYRESOURCEREQUEST']._serialized_end=85
  _globals['_APPLYRESOURCERESPONSE']._serialized_start=88
  _globals['_APPLYRESOURCERESPONSE']._serialized_end=245
  _globals['_APPLYRESOURCERESPONSE_HEADERSENTRY']._serialized_start=199
  _globals['_APPLYRESOURCERESPONSE_HEADERSENTRY']._serialized_end=245
  _globals['_RESOURCESERVICE']._serialized_start=247
  _globals['_RESOURCESERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
