# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import task_pb2 as task__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in task_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/taskproto.TaskService/CreateTask',
                request_serializer=task__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=task__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.DescribeTask = channel.unary_unary(
                '/taskproto.TaskService/DescribeTask',
                request_serializer=task__pb2.DescribeTaskRequest.SerializeToString,
                response_deserializer=task__pb2.DescribeTaskResponse.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_unary(
                '/taskproto.TaskService/ExecuteTask',
                request_serializer=task__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=task__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)
        self.DropTask = channel.unary_unary(
                '/taskproto.TaskService/DropTask',
                request_serializer=task__pb2.DropTaskRequest.SerializeToString,
                response_deserializer=task__pb2.DropTaskResponse.FromString,
                _registered_method=True)
        self.AlterTask = channel.unary_unary(
                '/taskproto.TaskService/AlterTask',
                request_serializer=task__pb2.AlterTaskRequest.SerializeToString,
                response_deserializer=task__pb2.AlterTaskResponse.FromString,
                _registered_method=True)
        self.ShowTasks = channel.unary_unary(
                '/taskproto.TaskService/ShowTasks',
                request_serializer=task__pb2.ShowTasksRequest.SerializeToString,
                response_deserializer=task__pb2.ShowTasksResponse.FromString,
                _registered_method=True)
        self.ShowTaskRuns = channel.unary_unary(
                '/taskproto.TaskService/ShowTaskRuns',
                request_serializer=task__pb2.ShowTaskRunsRequest.SerializeToString,
                response_deserializer=task__pb2.ShowTaskRunsResponse.FromString,
                _registered_method=True)
        self.GetTaskDependents = channel.unary_unary(
                '/taskproto.TaskService/GetTaskDependents',
                request_serializer=task__pb2.GetTaskDependentsRequest.SerializeToString,
                response_deserializer=task__pb2.GetTaskDependentsResponse.FromString,
                _registered_method=True)
        self.EnableTaskDependents = channel.unary_unary(
                '/taskproto.TaskService/EnableTaskDependents',
                request_serializer=task__pb2.EnableTaskDependentsRequest.SerializeToString,
                response_deserializer=task__pb2.EnableTaskDependentsResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTaskRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskDependents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableTaskDependents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=task__pb2.CreateTaskRequest.FromString,
                    response_serializer=task__pb2.CreateTaskResponse.SerializeToString,
            ),
            'DescribeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeTask,
                    request_deserializer=task__pb2.DescribeTaskRequest.FromString,
                    response_serializer=task__pb2.DescribeTaskResponse.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=task__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=task__pb2.ExecuteTaskResponse.SerializeToString,
            ),
            'DropTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTask,
                    request_deserializer=task__pb2.DropTaskRequest.FromString,
                    response_serializer=task__pb2.DropTaskResponse.SerializeToString,
            ),
            'AlterTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterTask,
                    request_deserializer=task__pb2.AlterTaskRequest.FromString,
                    response_serializer=task__pb2.AlterTaskResponse.SerializeToString,
            ),
            'ShowTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTasks,
                    request_deserializer=task__pb2.ShowTasksRequest.FromString,
                    response_serializer=task__pb2.ShowTasksResponse.SerializeToString,
            ),
            'ShowTaskRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTaskRuns,
                    request_deserializer=task__pb2.ShowTaskRunsRequest.FromString,
                    response_serializer=task__pb2.ShowTaskRunsResponse.SerializeToString,
            ),
            'GetTaskDependents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskDependents,
                    request_deserializer=task__pb2.GetTaskDependentsRequest.FromString,
                    response_serializer=task__pb2.GetTaskDependentsResponse.SerializeToString,
            ),
            'EnableTaskDependents': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableTaskDependents,
                    request_deserializer=task__pb2.EnableTaskDependentsRequest.FromString,
                    response_serializer=task__pb2.EnableTaskDependentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskproto.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskproto.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/CreateTask',
            task__pb2.CreateTaskRequest.SerializeToString,
            task__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/DescribeTask',
            task__pb2.DescribeTaskRequest.SerializeToString,
            task__pb2.DescribeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/ExecuteTask',
            task__pb2.ExecuteTaskRequest.SerializeToString,
            task__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/DropTask',
            task__pb2.DropTaskRequest.SerializeToString,
            task__pb2.DropTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlterTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/AlterTask',
            task__pb2.AlterTaskRequest.SerializeToString,
            task__pb2.AlterTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/ShowTasks',
            task__pb2.ShowTasksRequest.SerializeToString,
            task__pb2.ShowTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowTaskRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/ShowTaskRuns',
            task__pb2.ShowTaskRunsRequest.SerializeToString,
            task__pb2.ShowTaskRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskDependents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/GetTaskDependents',
            task__pb2.GetTaskDependentsRequest.SerializeToString,
            task__pb2.GetTaskDependentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableTaskDependents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskproto.TaskService/EnableTaskDependents',
            task__pb2.EnableTaskDependentsRequest.SerializeToString,
            task__pb2.EnableTaskDependentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
