# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import udf_pb2 as udf__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in udf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UdfServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyUdfResource = channel.unary_unary(
                '/udfproto.UdfService/ApplyUdfResource',
                request_serializer=udf__pb2.ApplyUdfResourceRequest.SerializeToString,
                response_deserializer=udf__pb2.ApplyUdfResourceResponse.FromString,
                _registered_method=True)


class UdfServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApplyUdfResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UdfServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyUdfResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyUdfResource,
                    request_deserializer=udf__pb2.ApplyUdfResourceRequest.FromString,
                    response_serializer=udf__pb2.ApplyUdfResourceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'udfproto.UdfService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('udfproto.UdfService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UdfService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplyUdfResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udfproto.UdfService/ApplyUdfResource',
            udf__pb2.ApplyUdfResourceRequest.SerializeToString,
            udf__pb2.ApplyUdfResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
