// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `common_storage` will provide storage related types and functions.
//!
//! Databend Query will have three kinds of storage operators, visit
//! [RFC: Cache](https://docs.databend.com/guides/community/rfcs/cache) for
//! more detailed information.
//!
//! - data operator: All data will be persisted until users delete them.
//! - cache operator: Backends could have their GC or background auto eviction logic, which means cache services is non-persist.
//! - temporary operator: Backend will be configured with TTL and timely delete old data.
//!
//! Users can use different operator based on their own needs, for example:
//!
//! - Users table data must be accessed via data operator
//! - Table snapshots, segments cache must be stored accessed via cache operator.
//! - Intermediate data generated by query could be stored by temporary operator.

#![allow(clippy::uninlined_format_args)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::let_unit_value)]
#![feature(box_patterns)]

mod auth;
pub use auth::RefreshableToken;
pub use auth::TokenFile;

mod config;
mod endpoint_policy;
pub use config::EndpointPolicyScope;
pub use config::EndpointUrlPolicy;
pub use config::EndpointUrlPolicyConfig;
pub use config::ShareTableConfig;
pub use config::StagePathTraversalPolicy;
pub use config::StorageConfig;
pub use endpoint_policy::EndpointUrlPolicyRegistry;
pub use endpoint_policy::check_storage_endpoint_url;
pub use endpoint_policy::check_storage_params_endpoints;

mod concurrent_limit_layer;
pub use concurrent_limit_layer::ConcurrentLimitLayer;

mod http_client;
pub use http_client::StorageHttpClient;

mod operator;
pub use operator::DataOperator;
pub use operator::IcebergFileIO;
pub use operator::OperatorRegistry;
pub use operator::check_operator;
pub use operator::init_operator;
pub use operator::init_operator_with_policy_scope;

mod operator_cache;

pub mod metrics;
pub use crate::metrics::StorageMetrics;
pub use crate::metrics::StorageMetricsLayer;

mod runtime_layer;

mod column_node;
pub use column_node::ColumnNode;
pub use column_node::ColumnNodes;

pub mod parquet;
pub use parquet::read_metadata_async;
pub use parquet::read_parquet_schema_async_rs;

mod stage;
pub use stage::STDIN_FD;
pub use stage::StageFileInfo;
pub use stage::StageFileInfoStream;
pub use stage::StageFileStatus;
pub use stage::StageFilesInfo;
pub use stage::ensure_no_stage_path_traversal;
pub use stage::init_stage_operator;
pub use stage::is_stage_path_traversal;

mod copy;
mod merge;
mod meta_hll;
mod metrics_layer;

pub use copy::CopyStatus;
pub use copy::FileParseError;
pub use copy::FileParseErrorAtLine;
pub use copy::FileStatus;
pub use merge::MutationStatus;
pub use meta_hll::MetaHLL;
pub use meta_hll::MetaHLL12;
