// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::cmp::Ordering;
use std::fmt::Write;
use std::num::IntErrorKind;
use std::num::ParseIntError;

use itertools::Itertools;
use ordered_float::OrderedFloat;

use crate::Range;
use crate::parser::common::transform_span;
use crate::parser::input::Input;
use crate::parser::token::*;
use crate::span::pretty_print_error;

const MAX_DISPLAY_ERROR_COUNT: usize = 60;

/// An error propagated along the active parse branch.
///
/// The `alt` combinator keeps the farthest error and merges candidates only
/// when they occur at the same input position.
#[derive(Debug)]
pub struct Error {
    /// The span of the next token of the last valid one when encountering an error.
    pub span: Range,
    /// List of errors tried in various branches that consumed
    /// the same (farthest) length of input.
    pub errors: Vec<ErrorKind>,
    /// Parser contexts collected while the error propagates outward.
    pub contexts: Vec<(Range, &'static str)>,
}

/// ErrorKind is the error type returned from parser.
#[derive(Debug, PartialEq, Eq)]
pub enum ErrorKind {
    /// Error generated by `match_token` function
    ExpectToken(TokenKind),
    /// Error generated by `match_text` function
    ExpectText(&'static str),
    /// Plain text description of an error
    Other(String),
}

impl ErrorKind {
    pub fn other(message: impl Into<String>) -> Self {
        Self::Other(message.into())
    }
}

impl<'a> nom::error::ParseError<Input<'a>> for Error {
    fn from_error_kind(i: Input<'a>, _: nom::error::ErrorKind) -> Self {
        Error {
            span: transform_span(&i[..1]).unwrap(),
            errors: vec![],
            contexts: vec![],
        }
    }

    fn append(_: Input<'a>, _: nom::error::ErrorKind, other: Self) -> Self {
        other
    }

    fn from_char(_: Input<'a>, _: char) -> Self {
        unreachable!()
    }

    fn or(mut self, mut other: Self) -> Self {
        match self.span.start.cmp(&other.span.start) {
            Ordering::Equal => {
                self.errors.append(&mut other.errors);
                self.contexts.clear();
                self
            }
            Ordering::Less => other,
            Ordering::Greater => self,
        }
    }
}

impl<'a> nom::error::ContextError<Input<'a>> for Error {
    fn add_context(input: Input<'a>, ctx: &'static str, mut other: Self) -> Self {
        other
            .contexts
            .push((transform_span(&input.tokens[..1]).unwrap(), ctx));
        other
    }
}

impl Error {
    pub fn from_error_kind(input: Input<'_>, kind: ErrorKind) -> Self {
        Error {
            span: transform_span(&input.tokens[..1]).unwrap(),
            errors: vec![kind],
            contexts: vec![],
        }
    }

    pub(crate) fn from_expected_tokens(input: Input<'_>, kinds: &'static [TokenKind]) -> Self {
        Error {
            span: transform_span(&input.tokens[..1]).unwrap(),
            errors: kinds.iter().copied().map(ErrorKind::ExpectToken).collect(),
            contexts: vec![],
        }
    }
}

impl From<fast_float2::Error> for ErrorKind {
    fn from(_: fast_float2::Error) -> Self {
        ErrorKind::other("unable to parse float number")
    }
}

impl From<ParseIntError> for ErrorKind {
    fn from(err: ParseIntError) -> Self {
        let msg = match err.kind() {
            IntErrorKind::InvalidDigit => {
                "unable to parse number because it contains invalid characters"
            }
            IntErrorKind::PosOverflow => "unable to parse number because it positively overflowed",
            IntErrorKind::NegOverflow => "unable to parse number because it negatively overflowed",
            _ => "unable to parse number",
        };
        ErrorKind::other(msg)
    }
}

impl From<hex::FromHexError> for ErrorKind {
    fn from(err: hex::FromHexError) -> Self {
        let msg = match err {
            hex::FromHexError::InvalidHexCharacter { .. } => {
                "unable to parse hex literal because it contains invalid characters"
            }
            hex::FromHexError::OddLength => {
                "unable to parse hex literal because it has an odd number of digits"
            }
            hex::FromHexError::InvalidStringLength => {
                "unable to parse hex literal because it has an invalid length"
            }
        };
        ErrorKind::other(msg)
    }
}

/// Suggests corrections using intelligent syntax pattern matching
fn suggest_keyword_correction(
    _span_text: &str,
    source: &str,
    _expected_tokens: &[String],
) -> Option<String> {
    use crate::parser::error_suggestion::suggest_correction;

    suggest_correction(source)
}

pub fn display_parser_error(error: Error, source: &str) -> String {
    let span_text = &source[std::ops::Range::from(error.span)];

    let mut labels = vec![];

    // Plain text error has the highest priority. Only display it if exists.
    for kind in &error.errors {
        if let ErrorKind::Other(msg) = kind {
            labels = vec![(error.span, msg.clone())];
            break;
        }
    }

    // List all expected tokens in alternative branches.
    if labels.is_empty() {
        let mut expected_tokens = error
            .errors
            .iter()
            .filter_map(|kind| match kind {
                ErrorKind::ExpectToken(EOI) => Some("end of input".to_string()),
                ErrorKind::ExpectToken(token) if token.is_keyword() => {
                    Some(format!("`{:?}`", token))
                }
                ErrorKind::ExpectToken(token) => Some(format!("<{:?}>", token)),
                ErrorKind::ExpectText(text) => Some(format!("`{}`", text)),
                _ => None,
            })
            .unique()
            .collect::<Vec<_>>();
        expected_tokens.sort_by_cached_key(|token| {
            OrderedFloat::from(-strsim::jaro_winkler(
                &token.to_lowercase(),
                &span_text.to_lowercase(),
            ))
        });

        // Check for intelligent keyword suggestions first
        let has_suggestion = suggest_keyword_correction(span_text, source, &expected_tokens);
        let mut msg = if span_text.is_empty() {
            "unexpected end of input".to_string()
        } else if all_reserved_keywords()
            .any(|keyword| keyword.to_lowercase() == span_text.to_lowercase())
            && has_suggestion.is_none()
        {
            format!("unexpected `{span_text}`. it's reserved keyword, you may avoid using it")
        } else {
            format!("unexpected `{span_text}`")
        };
        if let Some(suggestion) = has_suggestion {
            write!(msg, ". {}", suggestion).unwrap();
            labels = vec![(error.span, msg)];

            // Return early to skip context labels when we have intelligent suggestions
            return pretty_print_error(source, labels);
        } else {
            let mut iter = expected_tokens.iter().enumerate().peekable();
            while let Some((i, error)) = iter.next() {
                if i == MAX_DISPLAY_ERROR_COUNT {
                    let more = expected_tokens
                        .len()
                        .saturating_sub(MAX_DISPLAY_ERROR_COUNT);
                    write!(msg, ", or {} more ...", more).unwrap();
                    break;
                } else if i == 0 {
                    msg += ", expecting ";
                } else if iter.peek().is_none() && i == 1 {
                    msg += " or ";
                } else if iter.peek().is_none() {
                    msg += ", or ";
                } else {
                    msg += ", ";
                }
                msg += error;
            }

            labels = vec![(error.span, msg)];
        }
    }

    // Append contexts as secondary labels.
    labels.extend(
        error
            .contexts
            .iter()
            .filter(|(span, ctx)| {
                if *ctx != "expression" {
                    return true;
                }

                let start = span.start.min(error.span.start) as usize;
                let end = span.end.max(error.span.end) as usize;
                !source[start..end].contains('\n')
            })
            .map(|(span, msg)| (*span, format!("while parsing {}", msg))),
    );

    pretty_print_error(source, labels)
}
