SELECT '=== const ===';
SELECT EXPORT_SET(16, 'YYYY', 'NNN');
SELECT EXPORT_SET(16, 'YYYY', 'NNN', '_ABCDEFGH_');
SELECT EXPORT_SET(16, 'YYYY', 'NNN', '_ABCDEFGH_', 8);
SELECT EXPORT_SET(16, 'YYYY', 'NNN', '_ABCDEFGH_', 64);
SELECT EXPORT_SET(16, 'YYYY', 'NNN', '_ABCDEFGH_', 128);
SELECT EXPORT_SET(0, 'YYYY', 'NNN', '_ABCDEFGH_', 8);

SELECT '=== series ===';
SELECT '=== EXPORT_SET(number, number,   number,   number,   number) ===';
SELECT EXPORT_SET(number, number,   number,   number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   number,   number,   number) ===';
SELECT EXPORT_SET(16,    number,   number,   number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, number,   number,   number) ===';
SELECT EXPORT_SET(number, 'YY', number,   number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, number,   number,   number) ===';
SELECT EXPORT_SET(16,    'YY', number,   number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   NN, number,   number) ===';
SELECT EXPORT_SET(number, number,   'NN', number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   NN, number,   number) ===';
SELECT EXPORT_SET(16,    number,   'NN', number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, NN, number,   number) ===';
SELECT EXPORT_SET(number, 'YY', 'NN', number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, NN, number,   number) ===';
SELECT EXPORT_SET(16,    'YY', 'NN', number,   number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   number,   ::, number) ===';
SELECT EXPORT_SET(number, number,   number,   '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   number,   ::, number) ===';
SELECT EXPORT_SET(16,    number,   number,   '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, number,   ::, number) ===';
SELECT EXPORT_SET(number, 'YY', number,   '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, number,   ::, number) ===';
SELECT EXPORT_SET(16,    'YY', number,   '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   NN, ::, number) ===';
SELECT EXPORT_SET(number, number,   'NN', '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   NN, ::, number) ===';
SELECT EXPORT_SET(16,    number,   'NN', '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, NN, ::, number) ===';
SELECT EXPORT_SET(number, 'YY', 'NN', '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, NN, ::, number) ===';
SELECT EXPORT_SET(16,    'YY', 'NN', '::', number)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   number,   number,   11) ===';
SELECT EXPORT_SET(number, number,   number,   number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   number,   number,   11) ===';
SELECT EXPORT_SET(16,    number,   number,   number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, number,   number,   11) ===';
SELECT EXPORT_SET(number, 'YY', number,   number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, number,   number,   11) ===';
SELECT EXPORT_SET(16,    'YY', number,   number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   NN, number,   11) ===';
SELECT EXPORT_SET(number, number,   'NN', number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   NN, number,   11) ===';
SELECT EXPORT_SET(16,    number,   'NN', number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, NN, number,   11) ===';
SELECT EXPORT_SET(number, 'YY', 'NN', number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, NN, number,   11) ===';
SELECT EXPORT_SET(16,    'YY', 'NN', number,   11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   number,   ::, 11) ===';
SELECT EXPORT_SET(number, number,   number,   '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   number,   ::, 11) ===';
SELECT EXPORT_SET(16,    number,   number,   '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, number,   ::, 11) ===';
SELECT EXPORT_SET(number, 'YY', number,   '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, number,   ::, 11) ===';
SELECT EXPORT_SET(16,    'YY', number,   '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, number,   NN, ::, 11) ===';
SELECT EXPORT_SET(number, number,   'NN', '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    number,   NN, ::, 11) ===';
SELECT EXPORT_SET(16,    number,   'NN', '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(number, YY, NN, ::, 11) ===';
SELECT EXPORT_SET(number, 'YY', 'NN', '::', 11)  FROM numbers(5) ORDER BY number;
SELECT '=== EXPORT_SET(16,    YY, NN, ::, 11) ===';
SELECT EXPORT_SET(16,    'YY', 'NN', '::', 11)  FROM numbers(5) ORDER BY number;

SELECT '=== null ===';
SELECT EXPORT_SET(NULL, NULL,   NULL,   NULL,   NULL);
SELECT EXPORT_SET(1,    NULL,   NULL,   NULL,   NULL);
SELECT EXPORT_SET(NULL, 'NU_LL', NULL,   NULL,   NULL);
SELECT EXPORT_SET(1,    'NU_LL', NULL,   NULL,   NULL);
SELECT EXPORT_SET(NULL, NULL,   'NU_LL', NULL,   NULL);
SELECT EXPORT_SET(1,    NULL,   'NU_LL', NULL,   NULL);
SELECT EXPORT_SET(NULL, 'NU_LL', 'NU_LL', NULL,   NULL);
SELECT EXPORT_SET(1,    'NU_LL', 'NU_LL', NULL,   NULL);
SELECT EXPORT_SET(NULL, NULL,   NULL,   'NU_LL', NULL);
SELECT EXPORT_SET(1,    NULL,   NULL,   'NU_LL', NULL);
SELECT EXPORT_SET(NULL, 'NU_LL', NULL,   'NU_LL', NULL);
SELECT EXPORT_SET(1,    'NU_LL', NULL,   'NU_LL', NULL);
SELECT EXPORT_SET(NULL, NULL,   'NU_LL', 'NU_LL', NULL);
SELECT EXPORT_SET(1,    NULL,   'NU_LL', 'NU_LL', NULL);
SELECT EXPORT_SET(NULL, 'NU_LL', 'NU_LL', 'NU_LL', NULL);
SELECT EXPORT_SET(1,    'NU_LL', 'NU_LL', 'NU_LL', NULL);
SELECT EXPORT_SET(NULL, NULL,   NULL,   NULL,   1);
SELECT EXPORT_SET(1,    NULL,   NULL,   NULL,   1);
SELECT EXPORT_SET(NULL, 'NU_LL', NULL,   NULL,   1);
SELECT EXPORT_SET(1,    'NU_LL', NULL,   NULL,   1);
SELECT EXPORT_SET(NULL, NULL,   'NU_LL', NULL,   1);
SELECT EXPORT_SET(1,    NULL,   'NU_LL', NULL,   1);
SELECT EXPORT_SET(NULL, 'NU_LL', 'NU_LL', NULL,   1);
SELECT EXPORT_SET(1,    'NU_LL', 'NU_LL', NULL,   1);
SELECT EXPORT_SET(NULL, NULL,   NULL,   'NU_LL', 1);
SELECT EXPORT_SET(1,    NULL,   NULL,   'NU_LL', 1);
SELECT EXPORT_SET(NULL, 'NU_LL', NULL,   'NU_LL', 1);
SELECT EXPORT_SET(1,    'NU_LL', NULL,   'NU_LL', 1);
SELECT EXPORT_SET(NULL, NULL,   'NU_LL', 'NU_LL', 1);
SELECT EXPORT_SET(1,    NULL,   'NU_LL', 'NU_LL', 1);
SELECT EXPORT_SET(NULL, 'NU_LL', 'NU_LL', 'NU_LL', 1);
