SELECT CHAR_LENGTH(NULL);
SELECT CHAR_LENGTH('');
SELECT CHAR_LENGTH('hello world');
SELECT CHAR_LENGTH('早ab');

SELECT CHARACTER_LENGTH(NULL);
SELECT CHARACTER_LENGTH('');
SELECT CHARACTER_LENGTH('hello world');
SELECT CHARACTER_LENGTH('早ab');
