DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;

CREATE TABLE t1(c1 int) ENGINE = Null;
CREATE TABLE t2(c1 int) ENGINE = Null;
CREATE TABLE t3(c1 int) ENGINE = Null;

DROP DATABASE IF EXISTS ss;
DROP DATABASE IF EXISTS ss1;
DROP DATABASE IF EXISTS ss2;

CREATE DATABASE ss;
CREATE DATABASE ss1;
CREATE DATABASE ss2;


SHOW TABLES;

SHOW TABLES LIKE 't%';
SHOW TABLES LIKE 't2';
SHOW TABLES LIKE 't';

SHOW TABLES WHERE name LIKE 't%';
SHOW TABLES WHERE name = 't%' AND 1 = 0;
SHOW TABLES WHERE name = 't2' OR 1 = 1;
SHOW TABLES WHERE name = 't2' AND 1 = 1;

SHOW DATABASES WHERE DATABASE = 'ss';
SHOW DATABASES WHERE DATABASE like 'ss%';
SHOW DATABASES like 'ss%';
SHOW DATABASES like SUBSTRING('ss%' FROM 1 FOR 3);

DROP DATABASE IF EXISTS ss;
DROP DATABASE IF EXISTS ss1;
DROP DATABASE IF EXISTS ss2;

DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;
