DROP DATABASE IF EXISTS ss;
DROP DATABASE IF EXISTS ss1;
DROP DATABASE IF EXISTS ss2;

CREATE DATABASE ss;
CREATE DATABASE ss1;
CREATE DATABASE ss2;

SHOW DATABASES WHERE DATABASE = 'ss';
SHOW DATABASES WHERE DATABASE like 'ss%';
SHOW DATABASES like 'ss%';

DROP DATABASE IF EXISTS ss;
DROP DATABASE IF EXISTS ss1;
DROP DATABASE IF EXISTS ss2;