DROP DATABASE IF EXISTS db1;
CREATE DATABASE db1;
USE db1;

CREATE TABLE IF NOT EXISTS t(a varchar, b varchar);
INSERT INTO t(a,b) VALUES('1', 'v1'),('2','v2');
SELECT * FROM t;

DROP TABLE t;
CREATE TABLE IF NOT EXISTS t(a varchar, b varchar);
SELECT * FROM t;
