-- Alter table rename
DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;

CREATE TABLE t0(a int);
INSERT INTO TABLE t0 values(1);
SELECT * FROM t0;

ALTER TABLE t0 RENAME TO t1;
ALTER TABLE t0 RENAME TO t1; -- {ErrorCode 1025}
ALTER TABLE IF EXISTS t0 RENAME TO t1;
DROP TABLE t0; -- {ErrorCode 1025}
SELECT * FROM t1;

ALTER TABLE t1 RENAME TO system.t1; -- {ErrorCode 1002}
DROP TABLE IF EXISTS t1;
