// Copyright 2021 Datafuse Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Table lock v2 uses a separate meta-service keyspace and PutSequential.
//!
//! Key-value layout:
//! - `__fd_table_lock_v2/<tenant>/<table_id>/<revision>` -> `LockMeta`
//! - `revision` is the 21-digit, underscore-grouped suffix generated by
//!   `PutSequential`, e.g. `000_000_000_000_000_000_001`.
//! - `__fd_table_lock_v2_seq` stores the global sequence counter used by
//!   `PutSequential`; it is outside the lock-row prefix so listing locks only
//!   returns lock rows.
//! - Each lock row is written with the lock TTL and is periodically extended by
//!   the lock holder.
//!
//! Acquire algorithm:
//! 1. Insert a lock row with `PutSequential`; the generated suffix is the lock
//!    revision.
//! 2. List all rows under the same `<tenant>/<table_id>` prefix and sort by the
//!    numeric revision.
//! 3. The smallest revision owns the table lock and marks the row as acquired by
//!    extending it with `acquired_on`.
//! 4. Other waiters watch the delete event of their immediate predecessor, then
//!    repeat the list-and-check loop.
//! 5. Releasing the lock deletes the row; if a holder dies, TTL expiration
//!    eventually removes the row and lets the next waiter continue.
//!
//! The v2 keyspace is intentionally independent from the v1 table-lock keyspace.
//! During a rolling upgrade, old and new servers may acquire their own queue
//! entries concurrently; table metadata commit OCC still rejects conflicting
//! commits.

use std::io;

use chrono::Utc;
use databend_common_meta_app::KeyWithTenant;
use databend_common_meta_app::app_error::AppError;
use databend_common_meta_app::app_error::TableLockExpired;
use databend_common_meta_app::schema::CreateLockRevReply;
use databend_common_meta_app::schema::CreateLockRevReq;
use databend_common_meta_app::schema::DeleteLockRevReq;
use databend_common_meta_app::schema::ExtendLockRevReq;
use databend_common_meta_app::schema::ListLockRevReq;
use databend_common_meta_app::schema::ListLocksReq;
use databend_common_meta_app::schema::LockInfo;
use databend_common_meta_app::schema::LockMeta;
use databend_common_meta_app::schema::TableLockIdentV2;
use databend_common_meta_app::schema::table_lock_ident_v2::TABLE_LOCK_SEQ_KEY_V2;
use databend_meta_client::kvapi;
use databend_meta_client::kvapi::DirName;
use databend_meta_client::kvapi::ListOptions;
use databend_meta_client::kvapi::StructKey;
use databend_meta_client::types::InvalidReply;
use databend_meta_client::types::MetaError;
use databend_meta_client::types::TxnOp;
use databend_meta_client::types::TxnRequest;
use fastrace::func_name;
use futures::TryStreamExt;
use log::debug;

use crate::kv_app_error::KVAppError;
use crate::kv_pb_api::KVPbApi;
use crate::kv_pb_api::encode_pb;
use crate::kv_pb_crud_api::KVPbCrudApi;
use crate::txn_core_util::send_txn;

/// LockApi2 stores table locks in a separate keyspace and creates revisions with PutSequential.
#[async_trait::async_trait]
pub trait LockApi2
where
    Self: Send + Sync,
    Self: kvapi::KVApi<Error = MetaError>,
{
    #[fastrace::trace]
    async fn list_lock_revisions_v2(
        &self,
        req: ListLockRevReq,
    ) -> Result<Vec<(u64, LockMeta)>, KVAppError> {
        let dir = req.lock_key.gen_v2_prefix();
        let mut strm = self.list_pb(ListOptions::unlimited(&dir)).await?;

        let mut list = Vec::new();
        while let Some(itm) = strm.try_next().await? {
            let revision = itm
                .key
                .try_revision()
                .map_err(|e| invalid_reply(format!("invalid table lock v2 revision: {}", e)))?;
            list.push((revision, itm.seqv.data));
        }

        Ok(list)
    }

    #[logcall::logcall]
    #[fastrace::trace]
    async fn create_lock_revision_v2(
        &self,
        req: CreateLockRevReq,
    ) -> Result<CreateLockRevReply, KVAppError> {
        debug!(req :? =(&req); "LockApi2: {}", func_name!());

        let lock_key = &req.lock_key;
        let lock_meta = LockMeta {
            user: req.user,
            node: req.node,
            query_id: req.query_id,
            created_on: Utc::now(),
            acquired_on: None,
            lock_type: lock_key.lock_type(),
            extra_info: lock_key.get_extra_info(),
        };

        let buf = encode_pb(&lock_meta);
        let op = TxnOp::put_sequential(
            lock_key.gen_v2_prefix().dir_name_with_slash(),
            TABLE_LOCK_SEQ_KEY_V2,
            buf,
        )
        .with_ttl(Some(req.ttl));

        let txn_req = TxnRequest::new(vec![], vec![op]);
        let (success, responses) = send_txn(self, txn_req).await?;
        if !success {
            return Err(invalid_reply(
                "PutSequential transaction unexpectedly failed",
            ));
        }

        let Some(put) = responses.first().and_then(|resp| resp.try_as_put()) else {
            return Err(invalid_reply("PutSequential did not return a put response"));
        };

        let key = TableLockIdentV2::from_str_key(&put.key).map_err(|e| {
            invalid_reply(format!("invalid table lock v2 key '{}': {}", put.key, e))
        })?;

        Ok(CreateLockRevReply {
            revision: key
                .try_revision()
                .map_err(|e| invalid_reply(format!("invalid table lock v2 revision: {}", e)))?,
        })
    }

    #[logcall::logcall]
    #[fastrace::trace]
    async fn extend_lock_revision_v2(&self, req: ExtendLockRevReq) -> Result<(), KVAppError> {
        debug!(req :? =(&req); "LockApi2: {}", func_name!());

        let ctx = func_name!();

        let lock_key = &req.lock_key;
        let table_id = lock_key.get_table_id();
        let key = lock_key.gen_v2_key(req.revision);

        self.crud_update_existing(
            &key,
            |mut lock_meta| {
                if req.acquire_lock {
                    lock_meta.acquired_on = Some(Utc::now());
                }
                Some((lock_meta, Some(req.ttl)))
            },
            || {
                Err(AppError::TableLockExpired(TableLockExpired::new(
                    table_id, ctx,
                )))
            },
        )
        .await??;
        Ok(())
    }

    #[logcall::logcall]
    #[fastrace::trace]
    async fn delete_lock_revision_v2(&self, req: DeleteLockRevReq) -> Result<(), KVAppError> {
        debug!(req :? =(&req); "LockApi2: {}", func_name!());

        let key = req.lock_key.gen_v2_key(req.revision);
        self.crud_remove(&key, || Ok::<(), ()>(())).await?.unwrap();

        Ok(())
    }

    #[logcall::logcall]
    #[fastrace::trace]
    async fn list_locks_v2(&self, req: ListLocksReq) -> Result<Vec<LockInfo>, KVAppError> {
        let mut reply = vec![];
        for dir in &req.prefixes {
            let table_id = dir.key().table_id();
            let lock = TableLockIdentV2::new(dir.key().tenant().clone(), table_id, 0);
            let dir = if table_id == 0 {
                DirName::new_with_level(lock, 2)
            } else {
                DirName::new(lock)
            };

            let mut strm = self.list_pb(ListOptions::unlimited(&dir)).await?;
            while let Some(itm) = strm.try_next().await? {
                let revision = itm
                    .key
                    .try_revision()
                    .map_err(|e| invalid_reply(format!("invalid table lock v2 revision: {}", e)))?;
                reply.push(LockInfo {
                    table_id: itm.key.table_id(),
                    revision,
                    meta: itm.seqv.data,
                });
            }
        }
        Ok(reply)
    }
}

fn invalid_reply(msg: impl ToString) -> KVAppError {
    let msg = msg.to_string();
    let source = io::Error::new(io::ErrorKind::InvalidData, msg.clone());
    InvalidReply::new(msg, &source).into()
}

#[async_trait::async_trait]
impl<KV> LockApi2 for KV
where
    KV: Send + Sync,
    KV: kvapi::KVApi<Error = MetaError> + ?Sized,
{
}
